export const DEFAULTS = {
  members: ["NARR", "SHIVU"],
  income: [
    // Excel Financial Plan: NARR=55000 (planned), SHIVU=100000
    // May actual: NARR=68000, SHIVU=100000 → keeping actuals as defaults
    { id: "i1", label: "NARR Salary", subCat: "SALARY_NARR", amount: 55000 },
    { id: "i2", label: "SHIVU Salary", subCat: "SALARY_SHIVU", amount: 100000 },
  ],
  fixedExpenses: [
    // Aligned with Excel "Financial Plan" sheet
    { id: "f1",  label: "House Rent",         subCat: "HOUSE RENT",            budget: 19500 },
    { id: "f2",  label: "Send to Home",        subCat: "SEND TO HOME",          budget: 15000 },
    { id: "f3",  label: "Light Bill",          subCat: "LIGHTBILL",             budget: 2000  },
    { id: "f4",  label: "Gas Bill",            subCat: "GAS BILL",              budget: 1500  },
    { id: "f5",  label: "WiFi + Phone Bill",   subCat: "WIFI + PHONE BILL",     budget: 500   },
    { id: "f6",  label: "Vegetables + Grocery",subCat: "VEGETABLES + GROCERY",  budget: 10000 },
    { id: "f7",  label: "Monthly SIP",         subCat: "MONTHLY SIP",           budget: 10000 },
    { id: "f8",  label: "Misc",                subCat: "MISC",                  budget: 5000  },
    { id: "f9",  label: "Mediclaim",           subCat: "MEDICLAIM",             budget: 5000  },
    { id: "f10", label: "RentMojo Items",      subCat: "RENTMOJO ITEMS",        budget: 1700  },
    { id: "f11", label: "Car & Scooty Wash",   subCat: "CAR AND SCOOTY WASH",   budget: 1100  },
  ],
  variableBudget: 20000,
  variableSubCats: [
    "ENTERTAINMENT",
    "CAFES/RESTAURANTS",
    "SUBSCRIPTIONS",
    "GIFTS",
    "ONLINE FOOD",
    "SHOPPING",
    "BODY CARE",
    "CREDIT CARD BILLS",
    "TRANSPORT",
  ],
  savings: [
    // Excel Financial Plan savings targets: each ₹13,700 except Personal Savings ₹10,000
    { id: "s1", label: "Travel Fund",     monthlyTarget: 13700, goalTarget: 300000 },
    { id: "s2", label: "Emergency Fund",  monthlyTarget: 13700, goalTarget: 500000 },
    { id: "s3", label: "Home Fund",       monthlyTarget: 13700, goalTarget: 1000000 },
    { id: "s4", label: "Car Fund",        monthlyTarget: 13700, goalTarget: 800000 },
    { id: "s5", label: "Personal Savings",monthlyTarget: 10000, goalTarget: 200000 },
  ],
  creditCards: [
    // Excel "Credit Card" sheet: Narr outstanding=94572, Shivu=68356 (code had 67606 — mismatch)
    { id: "cc1", name: "NARR Credit Card",  person: "NARR",  limit: 150000, initialOutstanding: 94572 },
    { id: "cc2", name: "SHIVU Credit Card", person: "SHIVU", limit: 150000, initialOutstanding: 68356 },
  ],
  ccMonthlyCharges: {},
  customTags: ["reimbursable", "birthday", "travel", "emergency", "work"],
};

// Seed transactions derived from May_2026 sheet (Excel serial 46143 = 2026-05-01, etc.)
export const SEED = [
  // INCOME
  { id: "t1",  date: "2026-05-01", category: "INCOME",           subCat: "SALARY_NARR",         spentOn: "Narr May Salary",              amount: 68000, person: "NARR",  note: "", tags: [] },
  { id: "t53", date: "2026-05-11", category: "INCOME",           subCat: "SALARY_SHIVU",        spentOn: "Shivu May Salary",             amount: 100000,person: "SHIVU", note: "", tags: [] },
  // CC PAYMENTS (mapped from CREDIT CARD BILLS sub-category)
  { id: "t2",  date: "2026-05-01", category: "CC PAYMENT",       subCat: "NARR Credit Card",    spentOn: "CC Payment Narr May",          amount: 59000, person: "NARR",  note: "May bill", tags: [], ccId: "cc1" },
  { id: "t14", date: "2026-05-07", category: "CC PAYMENT",       subCat: "SHIVU Credit Card",   spentOn: "CC Payment Shivu May",         amount: 59000, person: "SHIVU", note: "May bill", tags: [], ccId: "cc2" },
  // VARIABLE — CAFES/RESTAURANTS
  { id: "t3",  date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Breakfast 30th April",         amount: 210,   person: "NARR",  note: "", tags: [] },
  { id: "t4",  date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Coffee 30th April",            amount: 289,   person: "SHIVU", note: "", tags: [] },
  { id: "t16", date: "2026-05-07", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Evening snack",                amount: 458,   person: "NARR",  note: "", tags: [] },
  { id: "t17", date: "2026-05-08", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Lunch with Babu & Abhishek",   amount: 525,   person: "SHIVU", note: "", tags: [] },
  { id: "t20", date: "2026-05-09", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Coffee with Didi Jiju",        amount: 1103,  person: "SHIVU", note: "", tags: [] },
  { id: "t36", date: "2026-05-08", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Snacks/dinner Narayan office", amount: 175,   person: "NARR",  note: "", tags: [] },
  { id: "t37", date: "2026-05-09", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Dosa at Pune Mumbai Expressway",amount: 280,  person: "SHIVU", note: "", tags: [] },
  { id: "t38", date: "2026-05-09", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "MCD Coffee at Expressway",     amount: 490,   person: "NARR",  note: "", tags: [] },
  { id: "t40", date: "2026-05-10", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Subway at Surat Mumbai Highway",amount: 230,  person: "SHIVU", note: "", tags: [] },
  { id: "t42", date: "2026-05-10", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Jalaram Kathiyawadi Dinner",    amount: 891,   person: "SHIVU", note: "", tags: [] },
  { id: "t43", date: "2026-05-11", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Redbull",                      amount: 315,   person: "SHIVU", note: "", tags: [] },
  { id: "t45", date: "2026-05-11", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Lunch",                        amount: 1289,  person: "SHIVU", note: "", tags: [] },
  { id: "t50", date: "2026-05-10", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Dinner in Surat Hotel",        amount: 1019,  person: "NARR",  note: "", tags: [] },
  { id: "t51", date: "2026-05-09", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Water and cold drink",         amount: 210,   person: "NARR",  note: "", tags: [] },
  { id: "t66", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Panipuri",                     amount: 100,   person: "SHIVU", note: "", tags: [] },
  { id: "t67", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Momos",                        amount: 90,    person: "SHIVU", note: "", tags: [] },
  { id: "t68", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Dosa",                         amount: 220,   person: "SHIVU", note: "", tags: [] },
  { id: "t69", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Cold drink",                   amount: 150,   person: "SHIVU", note: "", tags: [] },
  { id: "t75", date: "2026-05-20", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Nashta in office",             amount: 65,    person: "NARR",  note: "", tags: [] },
  { id: "t85", date: "2026-05-22", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Gola at Vadodara",             amount: 200,   person: "NARR",  note: "", tags: [] },
  { id: "t87", date: "2026-05-23", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Cafe with Heli",               amount: 1050,  person: "NARR",  note: "", tags: [] },
  { id: "t88", date: "2026-05-23", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Bhai Bhai",                    amount: 270,   person: "NARR",  note: "", tags: [] },
  { id: "t89", date: "2026-05-23", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "MN Soda",                      amount: 175,   person: "NARR",  note: "", tags: [] },
  { id: "t91", date: "2026-05-24", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS",  spentOn: "Bombay Sandwich",              amount: 550,   person: "NARR",  note: "", tags: [] },
  // VARIABLE — ONLINE FOOD
  { id: "t5",  date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "ONLINE FOOD",        spentOn: "Pizza 30th April",             amount: 651,   person: "SHIVU", note: "", tags: [] },
  { id: "t10", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "ONLINE FOOD",        spentOn: "Eatsure Lunch",                amount: 625,   person: "SHIVU", note: "", tags: [] },
  { id: "t70", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "ONLINE FOOD",        spentOn: "Coke Blinkit",                 amount: 253,   person: "SHIVU", note: "", tags: [] },
  { id: "t73", date: "2026-05-19", category: "VARIABLE EXPENSES", subCat: "ONLINE FOOD",        spentOn: "Lunch",                        amount: 383,   person: "SHIVU", note: "", tags: [] },
  // VARIABLE — BODY CARE
  { id: "t6",  date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "BODY CARE",          spentOn: "Shopping Miniso",              amount: 390,   person: "NARR",  note: "", tags: [] },
  { id: "t8",  date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "BODY CARE",          spentOn: "Hair Color Narr",              amount: 2572,  person: "NARR",  note: "", tags: [] },
  { id: "t93", date: "2026-05-25", category: "VARIABLE EXPENSES", subCat: "BODY CARE",          spentOn: "Shivu Skin Doctor",            amount: 2589,  person: "NARR",  note: "", tags: [] },
  // VARIABLE — TRANSPORT
  { id: "t15", date: "2026-05-07", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Train Tickets to Vadodara",    amount: 1754,  person: "SHIVU", note: "", tags: ["travel"] },
  { id: "t18", date: "2026-05-09", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Cab Babu Home to DSK",         amount: 458,   person: "SHIVU", note: "", tags: [] },
  { id: "t19", date: "2026-05-09", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Cab DSK to Babu Home",         amount: 477,   person: "SHIVU", note: "", tags: [] },
  { id: "t22", date: "2026-05-10", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Petrol for Activa",            amount: 465,   person: "NARR",  note: "", tags: [] },
  { id: "t24", date: "2026-05-10", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Porter - Clothes from Babu",   amount: 326,   person: "SHIVU", note: "", tags: [] },
  { id: "t33", date: "2026-05-08", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Sofa Porter",                  amount: 1000,  person: "SHIVU", note: "", tags: [] },
  { id: "t44", date: "2026-05-11", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Mall Parking",                 amount: 20,    person: "SHIVU", note: "", tags: [] },
  { id: "t58", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Phoenix Mall parking",         amount: 60,    person: "SHIVU", note: "", tags: [] },
  { id: "t63", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Phoenix Mall parking 2",       amount: 100,   person: "SHIVU", note: "", tags: [] },
  { id: "t74", date: "2026-05-19", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Activa Service",               amount: 750,   person: "SHIVU", note: "", tags: [] },
  { id: "t80", date: "2026-05-21", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Vande Bharat Mumbai-Vadodara", amount: 2274,  person: "SHIVU", note: "", tags: ["travel"] },
  { id: "t81", date: "2026-05-21", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Pune to Mumbai train",         amount: 814,   person: "SHIVU", note: "", tags: ["travel"] },
  { id: "t83", date: "2026-05-22", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Auto to Pune station",         amount: 229,   person: "NARR",  note: "", tags: [] },
  { id: "t84", date: "2026-05-22", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Local at Mumbai",              amount: 10,    person: "NARR",  note: "", tags: [] },
  { id: "t86", date: "2026-05-24", category: "VARIABLE EXPENSES", subCat: "TRANSPORT",          spentOn: "Train Vadodara to Pune",       amount: 4000,  person: "NARR",  note: "", tags: ["travel"] },
  // VARIABLE — SHOPPING
  { id: "t32", date: "2026-05-08", category: "VARIABLE EXPENSES", subCat: "SHOPPING",           spentOn: "Sofa for Home",                amount: 2000,  person: "SHIVU", note: "", tags: [] },
  { id: "t39", date: "2026-05-09", category: "VARIABLE EXPENSES", subCat: "SHOPPING",           spentOn: "Socks at Sketchers",           amount: 898,   person: "NARR",  note: "", tags: [] },
  { id: "t52", date: "2026-05-12", category: "VARIABLE EXPENSES", subCat: "SHOPPING",           spentOn: "Sofa Cleaning UC",             amount: 750,   person: "SHIVU", note: "", tags: [] },
  { id: "t55", date: "2026-05-13", category: "VARIABLE EXPENSES", subCat: "SHOPPING",           spentOn: "Bedroom Door Lock",            amount: 250,   person: "SHIVU", note: "", tags: [] },
  { id: "t56", date: "2026-05-13", category: "VARIABLE EXPENSES", subCat: "SHOPPING",           spentOn: "Bedroom Door Lock Repair UC",  amount: 290,   person: "NARR",  note: "", tags: [] },
  { id: "t57", date: "2026-05-15", category: "VARIABLE EXPENSES", subCat: "SHOPPING",           spentOn: "Dress for Shivu",              amount: 850,   person: "SHIVU", note: "", tags: [] },
  { id: "t59", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "SHOPPING",           spentOn: "Superdry clothes",             amount: 27195, person: "SHIVU", note: "", tags: [] },
  { id: "t61", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "SHOPPING",           spentOn: "Narr Onitsuka Tiger shoes",    amount: 13000, person: "SHIVU", note: "", tags: [] },
  { id: "t76", date: "2026-05-19", category: "VARIABLE EXPENSES", subCat: "SHOPPING",           spentOn: "Three boxers",                 amount: 1000,  person: "SHIVU", note: "", tags: [] },
  // VARIABLE — SUBSCRIPTIONS
  { id: "t11", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "SUBSCRIPTIONS",      spentOn: "Hotstar subscription",         amount: 1500,  person: "SHIVU", note: "till April 2027", tags: [] },
  { id: "t71", date: "2026-05-18", category: "VARIABLE EXPENSES", subCat: "SUBSCRIPTIONS",      spentOn: "Netflix subscription",         amount: 649,   person: "SHIVU", note: "", tags: [] },
  { id: "t88b",date: "2026-05-21", category: "VARIABLE EXPENSES", subCat: "SUBSCRIPTIONS",      spentOn: "Kiwi Subscription",            amount: 1179,  person: "NARR",  note: "", tags: [] },
  { id: "t88c",date: "2026-05-26", category: "VARIABLE EXPENSES", subCat: "SUBSCRIPTIONS",      spentOn: "HDFC Card Fee",                amount: 80,    person: "NARR",  note: "", tags: [] },
  // VARIABLE — ENTERTAINMENT
  { id: "t25b",date: "2026-05-10", category: "VARIABLE EXPENSES", subCat: "ENTERTAINMENT",      spentOn: "Tea",                          amount: 40,    person: "NARR",  note: "", tags: [] },
  { id: "t8b", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "ENTERTAINMENT",      spentOn: "Mall Parking",                 amount: 20,    person: "NARR",  note: "", tags: [] },
  { id: "t90", date: "2026-05-24", category: "VARIABLE EXPENSES", subCat: "ENTERTAINMENT",      spentOn: "TimeZone",                     amount: 1300,  person: "NARR",  note: "", tags: [] },
  // FIXED EXPENSES
  { id: "t7",  date: "2026-05-01", category: "FIXED EXPENSES",    subCat: "GAS BILL",           spentOn: "Gas Bill April",               amount: 354,   person: "SHIVU", note: "", tags: [] },
  { id: "t9",  date: "2026-05-01", category: "FIXED EXPENSES",    subCat: "RENTMOJO ITEMS",     spentOn: "Rent Mojo",                    amount: 1613,  person: "SHIVU", note: "", tags: [] },
  { id: "t12", date: "2026-05-01", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Blinkit - door strip + dahi", amount: 246,   person: "SHIVU", note: "", tags: [] },
  { id: "t12b",date: "2026-05-01", category: "FIXED EXPENSES",    subCat: "MISC",               spentOn: "Dinner for Mummy 30th April",  amount: 156,   person: "NARR",  note: "", tags: [] },
  { id: "t12c",date: "2026-05-01", category: "FIXED EXPENSES",    subCat: "MISC",               spentOn: "Dinner for Mummy Papa",        amount: 297,   person: "NARR",  note: "", tags: [] },
  { id: "t13", date: "2026-05-10", category: "FIXED EXPENSES",    subCat: "MISC",               spentOn: "Mummy Papa Train to Surat",    amount: 2363,  person: "NARR",  note: "", tags: [] },
  { id: "t21", date: "2026-05-09", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Vegetables",                  amount: 350,   person: "NARR",  note: "", tags: [] },
  { id: "t21b",date: "2026-05-09", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Blinkit - Paneer + Chaas + Dahi + Ramen",amount:349,person:"SHIVU",note:"",tags:[]},
  { id: "t23", date: "2026-05-10", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Zepto - Imli Chutney etc",    amount: 301,   person: "SHIVU", note: "", tags: [] },
  { id: "t23b",date: "2026-05-10", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Idli Chutney",                amount: 54,    person: "NARR",  note: "", tags: [] },
  { id: "t26", date: "2026-05-10", category: "FIXED EXPENSES",    subCat: "MISC",               spentOn: "Water and Soda for Mummy",    amount: 168,   person: "NARR",  note: "", tags: [] },
  { id: "t29", date: "2026-05-07", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Milk Zepto",                  amount: 58,    person: "SHIVU", note: "", tags: [] },
  { id: "t30", date: "2026-05-07", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Face Wash Shivu",             amount: 398,   person: "SHIVU", note: "", tags: [] },
  { id: "t41", date: "2026-05-10", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Mangoes",                    amount: 900,   person: "SHIVU", note: "", tags: [] },
  { id: "t46", date: "2026-05-11", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Blinkit - milk, Dahi etc",   amount: 537,   person: "SHIVU", note: "", tags: [] },
  { id: "t47", date: "2026-05-11", category: "FIXED EXPENSES",    subCat: "WIFI + PHONE BILL",  spentOn: "Mobile Recharge Shivu",       amount: 123,   person: "SHIVU", note: "", tags: [] },
  { id: "t54", date: "2026-05-12", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "BigBasket - Vegetables + Grocery",amount:638,person:"SHIVU",note:"",tags:[]},
  { id: "t54b",date: "2026-05-12", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Zepto - Butter",             amount: 114,   person: "SHIVU", note: "", tags: [] },
  { id: "t54c",date: "2026-05-12", category: "FIXED EXPENSES",    subCat: "SEND TO HOME",       spentOn: "Sent to Home",                amount: 15000, person: "SHIVU", note: "", tags: [] },
  { id: "t57b",date: "2026-05-13", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Chunda",                     amount: 175,   person: "SHIVU", note: "", tags: [] },
  { id: "t57c",date: "2026-05-13", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Dahi, Milk and essentials",  amount: 802,   person: "NARR",  note: "", tags: [] },
  { id: "t64", date: "2026-05-18", category: "FIXED EXPENSES",    subCat: "MISC",               spentOn: "Amaze window glass check",    amount: 500,   person: "SHIVU", note: "", tags: [] },
  { id: "t72", date: "2026-05-19", category: "FIXED EXPENSES",    subCat: "HOUSE RENT",         spentOn: "Rent for June",               amount: 19000, person: "SHIVU", note: "", tags: [] },
  { id: "t77", date: "2026-05-20", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Blinkit - veggie + milk",    amount: 230,   person: "SHIVU", note: "", tags: [] },
  { id: "t78", date: "2026-05-21", category: "FIXED EXPENSES",    subCat: "MISC",               spentOn: "Car Wash",                   amount: 300,   person: "SHIVU", note: "", tags: [] },
  { id: "t79", date: "2026-05-21", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Shivu body wash + Narr face wash",amount:1318,person:"SHIVU",note:"",tags:[]},
  { id: "t79b",date: "2026-05-22", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Milk and chocolate",         amount: 237,   person: "SHIVU", note: "", tags: [] },
  { id: "t79c",date: "2026-05-22", category: "FIXED EXPENSES",    subCat: "WIFI + PHONE BILL",  spentOn: "Narr Phone Recharge",         amount: 209,   person: "SHIVU", note: "", tags: [] },
  { id: "t82", date: "2026-05-21", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Zepto - Bread and Paratha",  amount: 171,   person: "SHIVU", note: "", tags: [] },
  { id: "t82b",date: "2026-05-21", category: "FIXED EXPENSES",    subCat: "CAR AND SCOOTY WASH",spentOn: "Paid to Car Wash Guy",        amount: 1100,  person: "SHIVU", note: "", tags: [] },
  { id: "t86b",date: "2026-05-24", category: "FIXED EXPENSES",    subCat: "MISC",               spentOn: "Car Petrol",                  amount: 2000,  person: "NARR",  note: "", tags: [] },
  { id: "t92", date: "2026-05-24", category: "FIXED EXPENSES",    subCat: "LIGHTBILL",          spentOn: "Light Bill",                  amount: 1590,  person: "NARR",  note: "", tags: [] },
  { id: "t86c",date: "2026-05-22", category: "FIXED EXPENSES",    subCat: "VEGETABLES + GROCERY",spentOn: "Shampoo",                    amount: 10,    person: "NARR",  note: "", tags: [] },
];
