export const DEFAULTS = {
  members: ["NARR", "SHIVU"],
  income: [
    { id: "i1", label: "NARR Salary", amount: 68000 },
    { id: "i2", label: "SHIVU Salary", amount: 100000 },
  ],
  fixedExpenses: [
    { id: "f1", label: "House Rent", budget: 19500 },
    { id: "f2", label: "Send to Home", budget: 15000 },
    { id: "f3", label: "Light Bill", budget: 2000 },
    { id: "f4", label: "Gas Bill", budget: 1500 },
    { id: "f5", label: "WiFi Bill", budget: 500 },
    { id: "f6", label: "Grocery", budget: 10000 },
    { id: "f7", label: "Monthly SIP", budget: 10000 },
    { id: "f8", label: "Misc", budget: 5000 },
    { id: "f9", label: "Mediclaim", budget: 5000 },
    { id: "f10", label: "RentMojo Items", budget: 1700 },
  ],
  variableBudget: 20000,
  variableSubCats: [
    "ENTERTAINMENT",
    "CAFES/RESTAURANTS",
    "SUBSCRIPTIONS",
    "GIFTS",
    "ONLINE FOOD",
    "SHOPPING",
    "BODY CARE",
    "TRANSPORT",
  ],
  savings: [
    { id: "s1", label: "Travel Fund", monthlyTarget: 14950, goalTarget: 300000 },
    { id: "s2", label: "Emergency Fund", monthlyTarget: 14950, goalTarget: 500000 },
    { id: "s3", label: "Home Fund", monthlyTarget: 14950, goalTarget: 1000000 },
    { id: "s4", label: "Car Fund", monthlyTarget: 14950, goalTarget: 800000 },
    { id: "s5", label: "Personal Savings", monthlyTarget: 10000, goalTarget: 200000 },
  ],
  creditCards: [
    { id: "cc1", name: "NARR Credit Card", person: "NARR", limit: 150000, initialOutstanding: 94572 },
    { id: "cc2", name: "SHIVU Credit Card", person: "SHIVU", limit: 150000, initialOutstanding: 67606 },
  ],
  ccMonthlyCharges: {},
  customTags: ["reimbursable", "birthday", "travel", "emergency", "work"],
  openingBalances: { "2026-05": { NARR: 0, SHIVU: 0, note: "First month tracked" } },
};

export const SEED = [
  { id: "t1", date: "2026-05-01", category: "INCOME", subCat: "NARR Salary", spentOn: "Narr May Salary", amount: 68000, person: "NARR", note: "", tags: [] },
  { id: "t2", date: "2026-05-01", category: "CC PAYMENT", subCat: "NARR Credit Card", spentOn: "CC Payment Narr May", amount: 59000, person: "NARR", note: "May bill", tags: [], ccId: "cc1" },
  { id: "t3", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS", spentOn: "Breakfast 30 April", amount: 210, person: "NARR", note: "", tags: [] },
  { id: "t4", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS", spentOn: "Coffee 30 April", amount: 289, person: "SHIVU", note: "", tags: [] },
  { id: "t5", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "ONLINE FOOD", spentOn: "Pizza 30 April", amount: 651, person: "SHIVU", note: "", tags: [] },
  { id: "t6", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "BODY CARE", spentOn: "Shopping Miniso", amount: 390, person: "NARR", note: "", tags: [] },
  { id: "t7", date: "2026-05-01", category: "FIXED EXPENSES", subCat: "Gas Bill", spentOn: "Gas Bill April", amount: 354, person: "SHIVU", note: "", tags: [] },
  { id: "t8", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "BODY CARE", spentOn: "Hair Color Narr", amount: 2572, person: "NARR", note: "", tags: [] },
  { id: "t9", date: "2026-05-01", category: "FIXED EXPENSES", subCat: "RentMojo Items", spentOn: "Rent Mojo", amount: 1613, person: "SHIVU", note: "", tags: [] },
  { id: "t10", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "ONLINE FOOD", spentOn: "Eatsure Lunch", amount: 625, person: "SHIVU", note: "", tags: [] },
  { id: "t11", date: "2026-05-01", category: "VARIABLE EXPENSES", subCat: "SUBSCRIPTIONS", spentOn: "Hotstar", amount: 1500, person: "SHIVU", note: "", tags: [] },
  { id: "t12", date: "2026-05-01", category: "FIXED EXPENSES", subCat: "Grocery", spentOn: "Blinkit groceries", amount: 246, person: "SHIVU", note: "", tags: [] },
  { id: "t13", date: "2026-05-04", category: "FIXED EXPENSES", subCat: "Misc", spentOn: "Mummy Papa Train Surat", amount: 2363, person: "NARR", note: "", tags: [] },
  { id: "t14", date: "2026-05-07", category: "CC PAYMENT", subCat: "SHIVU Credit Card", spentOn: "CC Payment Shivu May", amount: 59000, person: "SHIVU", note: "May bill", tags: [], ccId: "cc2" },
  { id: "t15", date: "2026-05-07", category: "VARIABLE EXPENSES", subCat: "TRANSPORT", spentOn: "Train to Vadodara", amount: 1754, person: "SHIVU", note: "", tags: ["travel"] },
  { id: "t16", date: "2026-05-07", category: "VARIABLE EXPENSES", subCat: "CAFES/RESTAURANTS", spentOn: "Evening Snack", amount: 458, person: "NARR", note: "", tags: [] },
];
